In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [2]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt

Categories=['Femur Patho','Femur Sain']
flat_data_arr_train=[] #input array
target_arr_train=[] #output array
datadir='/content/drive/MyDrive/cartes_epaisseur' 
#path which contains all the categories of images

list_train = []
list_test = []
train_ids_fem_pato = [1,6,7,12,13,19,25]
test_ids_fem_pato = [20,22]
train_ids_fem_sain = [18,65,66,67,68,69]
test_ids_fem_sain = [71,74,60,62,64]

for i in train_ids_fem_pato:
    image_name = '/femur_patho/Femur_%02d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_fem_pato:
    image_name = '/femur_patho/Femur_%02d.png'%(i)
    list_test.append(datadir + image_name)

for i in train_ids_fem_sain:
    image_name = '/femur/Femur_%02d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_fem_sain:
    image_name = '/femur/Femur_%02d.png'%(i)
    list_test.append(datadir + image_name)



i=0
for img in list_train:
      img_array=imread(img)
      flat_data_arr_train.append(img_array.flatten())
      if i<len(train_ids_fem_pato):
        target_arr_train.append(Categories.index('Femur Patho'))
      else:
        target_arr_train.append(Categories.index('Femur Sain'))
      i+=1

flat_data_train=np.array(flat_data_arr_train)
target_train=np.array(target_arr_train)
df_train=pd.DataFrame(flat_data_train) #dataframe
df_train['Target']=target_train
x_train=df_train.iloc[:,:-1] #input data 
y_train=df_train.iloc[:,-1] #output data


In [3]:
flat_data_arr_test=[] #input array
target_arr_test=[] #output array

j=0
for img in list_test:
      img_array=imread(img)
      flat_data_arr_test.append(img_array.flatten())
      if j<len(test_ids_fem_pato):
        target_arr_test.append(Categories.index('Femur Patho'))
      else:
        target_arr_test.append(Categories.index('Femur Sain'))
      j+=1

flat_data_test=np.array(flat_data_arr_test)
target_test=np.array(target_arr_test)
df_test=pd.DataFrame(flat_data_test) #dataframe
df_test['Target']=target_test
x_test=df_test.iloc[:,:-1] #input data 
y_test=df_test.iloc[:,-1] #output data

In [4]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)

svc.fit(x_train,y_train)
print('The Model is trained well with the given images')
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)

The Model is trained well with the given images


GridSearchCV(estimator=SVC(probability=True),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.0001, 0.001, 0.1, 1],
                         'kernel': ['rbf', 'poly']})

In [6]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

y_pred=model.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_test,y_pred)*100}% accurate")
print("un petit text ", model.best_params_)
print("f1:")
print(f1_score(y_test,y_pred, average=None))
print("precision:")
print(precision_score(y_test,y_pred, average=None))
print("recall:")
print(recall_score(y_test,y_pred, average=None))

The predicted Data is :
[0 0 0 0 0 0 0]
The actual data is:
[0 0 1 1 1 1 1]
The model is 28.57142857142857% accurate
un petit text  {'C': 0.1, 'gamma': 0.0001, 'kernel': 'rbf'}
f1:
[0.44444444 0.        ]
precision:
[0.28571429 0.        ]
recall:
[1. 0.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Avec épaisseur

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

Categories=['Femur Patho','Femur Sain']
flat_data_arr_train=[] #input array
target_arr_train=[] #output array
datadir='/content/drive/MyDrive/new_cartes_epaisseur' 
#path which contains all the categories of images

list_train = []
list_test = []
train_ids_fem_pato = [1,6,7,8,9,10,12,13,14,20] #1,6,7,8,9,10,12,13,14,20,22,25
test_ids_fem_pato = [22,25]
train_ids_fem_sain = [59,60,62,63,64,65,67,68,69,70] #2,4,18,49,57,58,59,60,62,63,64,65,67,68,69,70,71,73,74,75
test_ids_fem_sain = [71,73,74,75]

for i in train_ids_fem_pato:
    image_name = '/Femur_patho/Mirrors_femur_bis/Femur_%02d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_fem_pato:
    image_name = '/Femur_patho/Mirrors_femur_bis/Femur_%02d.png'%(i)
    list_test.append(datadir + image_name)

for i in train_ids_fem_sain:
    image_name = '/Femur/Mirrors_femur_bis/Femur_%02d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_fem_sain:
    image_name = '/Femur/Mirrors_femur_bis/Femur_%02d.png'%(i)
    list_test.append(datadir + image_name)



i=0
for img in list_train:
      imag = Image.open(img)
      img_array = np.asarray(imag)
      flat_data_arr_train.append(img_array.flatten())
      if i<len(train_ids_fem_pato):
        target_arr_train.append(Categories.index('Femur Patho'))
      else:
        target_arr_train.append(Categories.index('Femur Sain'))
      i+=1

flat_data_train=np.array(flat_data_arr_train)
target_train=np.array(target_arr_train)
df_train=pd.DataFrame(flat_data_train) #dataframe
df_train['Target']=target_train
x_train=df_train.iloc[:,:-1] #input data 
y_train=df_train.iloc[:,-1] #output data

In [ ]:
flat_data_arr_test=[] #input array
target_arr_test=[] #output array

j=0
for img in list_test:
      imag = Image.open(img)
      img_array = np.asarray(imag)
      flat_data_arr_test.append(img_array.flatten())
      if j<len(test_ids_fem_pato):
        target_arr_test.append(Categories.index('Femur Patho'))
      else:
        target_arr_test.append(Categories.index('Femur Sain'))
      j+=1

flat_data_test=np.array(flat_data_arr_test)
target_test=np.array(target_arr_test)
df_test=pd.DataFrame(flat_data_test) #dataframe
df_test['Target']=target_test
x_test=df_test.iloc[:,:-1] #input data 
y_test=df_test.iloc[:,-1] #output data

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)

svc.fit(x_train,y_train)
print('The Model is trained well with the given images')
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)

The Model is trained well with the given images


GridSearchCV(estimator=SVC(probability=True),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.0001, 0.001, 0.1, 1],
                         'kernel': ['rbf', 'poly']})

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

y_pred=model.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_test,y_pred)*100}% accurate")
print("un petit text ", model.best_params_)
print("f1:")
f1_score(y_test,y_pred)
print("precision:")
precision_score(y_test,y_pred)
print("recall:")
recall_score(y_test,y_pred)

The predicted Data is :
[1 1 1 1 0 1]
The actual data is:
[0 0 1 1 1 1]
The model is 50.0% accurate
un petit text  {'C': 0.1, 'gamma': 0.0001, 'kernel': 'poly'}
