In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt

Categories=['Tibia Patho','Tibia Sain']
flat_data_arr_train=[] #input array
target_arr_train=[] #output array
datadir='/content/drive/MyDrive/cartes_epaisseur_Standford' 
#path which contains all the categories of images

list_train = []
list_test = []
train_ids_tib_pato = [6,30,45,53,66,71,83,84,87,105,126,139,140,150,152,154,156,158,167,172,183,186,189,194,200,201,207,218,224] #35 patho
test_ids_tib_pato = [227,229,230,237,241,245]
train_ids_tib_sain = [1,5,8,10,13,15,16,18,19,20,26,28,33,34,37,38,40,43,44,46,47,52,56,57,61,62,69,93]  
test_ids_tib_sain = [97,104,107,130,135,142]

for i in train_ids_tib_pato:
    image_name = '/Tibia_patho/Tibia_map/Tibia_%03d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_tib_pato:
    image_name = '/Tibia_patho/Tibia_map/Tibia_%03d.png'%(i)
    list_test.append(datadir + image_name)

for i in train_ids_tib_sain:
    image_name = '/Tibia/Tibia_map/Tibia_%03d.png'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_tib_sain:
    image_name = '/Tibia/Tibia_map/Tibia_%03d.png'%(i)
    list_test.append(datadir + image_name)



i=0
for img in list_train:
      img_array=imread(img)
      flat_data_arr_train.append(img_array.flatten())
      if i<len(train_ids_tib_pato):
        target_arr_train.append(Categories.index('Tibia Patho'))
      else:
        target_arr_train.append(Categories.index('Tibia Sain'))
      i+=1

flat_data_train=np.array(flat_data_arr_train)
target_train=np.array(target_arr_train)
df_train=pd.DataFrame(flat_data_train) #dataframe
df_train['Target']=target_train
x_train=df_train.iloc[:,:-1] #input data 
y_train=df_train.iloc[:,-1] #output data


In [8]:
flat_data_arr_test=[] #input array
target_arr_test=[] #output array

j=0
for img in list_test:
      img_array=imread(img)
      flat_data_arr_test.append(img_array.flatten())
      if j<len(test_ids_tib_pato):
        target_arr_test.append(Categories.index('Tibia Patho'))
      else:
        target_arr_test.append(Categories.index('Tibia Sain'))
      j+=1

flat_data_test=np.array(flat_data_arr_test)
target_test=np.array(target_arr_test)
df_test=pd.DataFrame(flat_data_test) #dataframe
df_test['Target']=target_test
x_test=df_test.iloc[:,:-1] #input data 
y_test=df_test.iloc[:,-1] #output data

In [9]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10],'gamma':[0.001,0.1],'kernel':['rbf','poly']} #C:100, gamma: 0.0001,1
svc=svm.SVC(probability=True)

svc.fit(x_train,y_train)
print('The Model is trained well with the given images')
#model=GridSearchCV(svc,param_grid)

The Model is trained well with the given images


In [10]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

y_pred=svc.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_test,y_pred)*100}% accurate")
print("f1:")
f1_score(y_test,y_pred)
print("precision:")
precision_score(y_test,y_pred)
print("recall:")
recall_score(y_test,y_pred)

The predicted Data is :
[1 0 0 1 1 1 0 1 1 0 1 1]
The actual data is:
[0 0 0 0 0 0 1 1 1 1 1 1]
The model is 50.0% accurate
f1:
precision:
recall:


0.6666666666666666

# A partir des épaisseurs

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

Categories=['Tibia Patho','Tibia Sain']
flat_data_arr_train=[] #input array
target_arr_train=[] #output array
datadir='/content/drive/MyDrive/new_cartes_epaisseur' 
#path which contains all the categories of images

list_train = []
list_test = []
train_ids_tib_pato = [1,2,3,4,6,9,10,12,13] # 1,2,3,4,6,9,10,12,13,19,18
test_ids_tib_pato = [19,18]
train_ids_tib_sain = [60,61,62,63,64,65,67,68,69]  #7,8,22,23,49,50,55,57,58,59,60,61,62,63,64,65,67,68,69,70,71,73,74,75
test_ids_tib_sain = [71,73,74,75]

for i in train_ids_tib_pato:
    image_name = '/Tibia_patho/Tibia_map/Tibia_%02d.tiff'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_tib_pato:
    image_name = '/Tibia_patho/Tibia_map/Tibia_%02d.tiff'%(i)
    list_test.append(datadir + image_name)

for i in train_ids_tib_sain:
    image_name = '/Tibia/Tibia_map/Tibia_%02d.tiff'%(i)
    list_train.append(datadir + image_name)

for i in test_ids_tib_sain:
    image_name = '/Tibia/Tibia_map/Tibia_%02d.tiff'%(i)
    list_test.append(datadir + image_name)



i=0
for img in list_train:
      imag = Image.open(img)
      img_array = np.asarray(imag)
      flat_data_arr_train.append(img_array.flatten())
      if i<len(train_ids_tib_pato):
        target_arr_train.append(Categories.index('Tibia Patho'))
      else:
        target_arr_train.append(Categories.index('Tibia Sain'))
      i+=1

flat_data_train=np.array(flat_data_arr_train)
target_train=np.array(target_arr_train)
df_train=pd.DataFrame(flat_data_train) #dataframe
df_train['Target']=target_train
x_train=df_train.iloc[:,:-1] #input data 
y_train=df_train.iloc[:,-1] #output data


In [ ]:
flat_data_arr_test=[] #input array
target_arr_test=[] #output array

j=0
for img in list_test:
      imag = Image.open(img)
      img_array = np.asarray(imag)
      flat_data_arr_test.append(img_array.flatten())
      if j<len(test_ids_tib_pato):
        target_arr_test.append(Categories.index('Tibia Patho'))
      else:
        target_arr_test.append(Categories.index('Tibia Sain'))
      j+=1

flat_data_test=np.array(flat_data_arr_test)
target_test=np.array(target_arr_test)
df_test=pd.DataFrame(flat_data_test) #dataframe
df_test['Target']=target_test
x_test=df_test.iloc[:,:-1] #input data 
y_test=df_test.iloc[:,-1] #output data

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)

svc.fit(x_train,y_train)
print('The Model is trained well with the given images')
#model=GridSearchCV(svc,param_grid)

The Model is trained well with the given images


In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

y_pred=svc.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_test,y_pred)*100}% accurate")
print("f1:")
f1_score(y_test,y_pred)
print("precision:")
precision_score(y_test,y_pred)
print("recall:")
recall_score(y_test,y_pred)

The predicted Data is :
[0 0 1 0 0 0]
The actual data is:
[0 0 1 1 1 1]
The model is 50.0% accurate
